/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Serving } from "./Serving.js";
export * as factories from "./factories/index.js";
export { Serving__factory } from "./factories/Serving__factory.js";
